In [10]:
import torch
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(f"Compute device: {device}\n")

count = torch.cuda.device_count()
print(f"GPUs: {count}")

for i in range(count):
    current = torch.cuda.current_device()
    name = torch.cuda.get_device_name(current)
    print(f" [{i}]: {name}")


#### A couple of actual operation
print("")
X = torch.FloatTensor([0., 1., 2.])

if torch.cuda.is_available():
	X = X.cuda() 

Y = X + 2

Z = Y.cpu()

for e in [X, Y, Z]:
	print(f"{e} on GPU: {e.is_cuda}")


Compute device: cpu

GPUs: 0

tensor([0., 1., 2.]) on GPU: False
tensor([2., 3., 4.]) on GPU: False
tensor([2., 3., 4.]) on GPU: False
